#
# LuaDist Travis-CI Hook
#

# We assume C build environments
language: C

# Try using multiple Lua Implementations
env:
  - TOOL="gcc"                  # Use native compiler (GCC usually)
  - TOOL="clang"                # Use clang
  - TOOL="i686-w64-mingw32"     # 32bit MinGW
  - TOOL="x86_64-w64-mingw32"   # 64bit MinGW
  - TOOL="arm-linux-gnueabihf"  # ARM hard-float (hf), linux

# Crosscompile builds may fail
matrix:
  allow_failures:
    - env: TOOL="i686-w64-mingw32"
    - env: TOOL="x86_64-w64-mingw32"
    - env: TOOL="arm-linux-gnueabihf"

# Install dependencies
install:
  - git clone git://github.com/LuaDist/Tools.git ~/_tools
  - ~/_tools/travis/travis install

# Bootstap
before_script:
  - ~/_tools/travis/travis bootstrap

# Build the module
script:
  - ~/_tools/travis/travis build
  - cd $TRAVIS_BUILD_DIR
  - /home/travis/build/moteus/lzlib/_test/bin/lua test_zlib3.lua
  - /home/travis/build/moteus/lzlib/_test/bin/lua test_zlib2.lua
  - /home/travis/build/moteus/lzlib/_test/bin/lua test_prologue.lua
  - /home/travis/build/moteus/lzlib/_test/bin/lua test_gzip.lua
  - /home/travis/build/moteus/lzlib/_test/bin/lua test_crc32.lua


# Execute additional tests or commands
after_script:
  - ~/_tools/travis/travis test

# Only watch the master branch
branches:
  only:
    - moteus

# Notify the LuaDist Dev group if needed
notifications:
  recipients:
    - luadist-dev@googlegroups.com
  email:
    on_success: change
    on_failure: always
